# Generated by Django 5.2.3 on 2025-06-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('consulta', 'Consulta general'), ('vacunacion', 'Vacunación y desparasitación'), ('cirugia', 'Cirugías'), ('nutricion', 'Control de peso y nutrición'), ('urgencia', 'Atención de urgencias'), ('laboratorio', 'Laboratorio clínico'), ('peluqueria', 'Baño y peluquería')], default='consulta', max_length=30),
        ),
    ]
